# Generated by Django 5.0.6 on 2026-09-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoSiaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_siaf', models.CharField(max_length=50, verbose_name='Código SIAF')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('unidad_medida', models.CharField(max_length=50, verbose_name='Unidad de Medida')),
                ('stock_unidades', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('tipo_almacen', models.CharField(choices=[('CENTRAL', 'Almacén Central (General)'), ('NUTRICION', 'Almacén de Nutrición'), ('LABORATORIO', 'Almacén de Laboratorio')], default='CENTRAL', max_length=20, verbose_name='Tipo de Almacén')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última Sincronización')),
            ],
            options={
                'verbose_name': 'Producto SIAF',
                'verbose_name_plural': 'Productos SIAF',
                'indexes': [models.Index(fields=['codigo_siaf', 'tipo_almacen'], name='siaf_sincro_codigo__ded6be_idx')],
                'unique_together': {('codigo_siaf', 'tipo_almacen')},
            },
        ),
    ]
