# Generated by Django 5.0.6 on 2026-09-08 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaf_sincro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('justificacion', models.TextField(verbose_name='Justificación o Destino')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado / Despachado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('codigo_pedido', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Nro. Pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Pedido de Almacén',
                'verbose_name_plural': 'Pedidos de Almacén',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.PositiveIntegerField(verbose_name='Cantidad Solicitada')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siaf_sincro.productosiaf', verbose_name='Producto SIAF')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='siaf_sincro.pedidoalmacen')),
            ],
            options={
                'verbose_name': 'Detalle del Pedido',
                'verbose_name_plural': 'Detalles del Pedido',
            },
        ),
    ]
