# Generated by Django 5.0.6 on 2026-09-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaf_sincro', '0002_pedidoalmacen_detallepedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoalmacen',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Autorización'), ('AUTORIZADO', 'Autorizado por Dirección/Admin'), ('ENTREGADO', 'Entregado / Despachado (Almacén)'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=40, verbose_name='Estado'),
        ),
    ]
