# Generated by Django 5.0.6 on 2026-09-09 16:20

# apps/siaf_sincro/migrations/xxxx_crear_grupos_almacen.py
from django.db import migrations

def crear_grupos_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    # Creamos los 3 roles de negocio puros
    Group.objects.get_or_create(name='Solicitantes_Almacen')
    Group.objects.get_or_create(name='Aprobadores_Almacen')
    Group.objects.get_or_create(name='Almaceneros_Almacen')

def eliminar_grupos_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Solicitantes_Almacen', 'Aprobadores_Almacen', 'Almaceneros_Almacen']).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('siaf_sincro', '0003_alter_pedidoalmacen_estado'), # Asegúrate de que apunte a tu primera migración
    ]
    operations = [
        migrations.RunPython(crear_grupos_roles, reverse_code=eliminar_grupos_roles),
    ]
