# Generated by Django 5.0.6 on 2026-09-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siaf_sincro', '0003_alter_pedidoalmacen_estado'),
        ('siaf_sincro', '0004_crear_grupos_almacen'),
    ]

    operations = [
    ]
