# Generated by Django 5.0.6 on 2026-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaf_sincro', '0005_merge_20260909_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={},
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='cantidad_despachada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad Despachada'),
        ),
    ]
