# Generated by Django 5.0.6 on 2026-09-11 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaf_sincro', '0006_alter_detallepedido_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoalmacen',
            name='fecha_autorizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización'),
        ),
        migrations.AddField(
            model_name='pedidoalmacen',
            name='firma_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Token Digital de Seguridad'),
        ),
        migrations.AddField(
            model_name='pedidoalmacen',
            name='usuario_autoriza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_autorizados', to=settings.AUTH_USER_MODEL, verbose_name='Autorizado por'),
        ),
    ]
