# Generated by Django 5.0.6 on 2026-09-11 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaf_sincro', '0007_pedidoalmacen_fecha_autorizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadHospitalaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Unidad/Servicio')),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código Interno (Opcional)')),
            ],
            options={
                'verbose_name': 'Unidad Hospitalaria',
                'verbose_name_plural': 'Unidades Hospitalarias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pedidoalmacen',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='siaf_sincro.unidadhospitalaria', verbose_name='Unidad Solicitante'),
        ),
    ]
