# Generated by Django 5.0.6 on 2026-09-22 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaf_sincro', '0008_unidadhospitalaria_pedidoalmacen_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscrepanciaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_siaf_csv', models.IntegerField(verbose_name='Stock en CSV (SIAF)')),
                ('stock_django_real', models.IntegerField(verbose_name='Stock Real en Django')),
                ('unidades_omitidas_siaf', models.PositiveIntegerField(verbose_name='Cantidad No Digitada en SIAF')),
                ('detectado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Detección')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancias', to='siaf_sincro.productosiaf')),
            ],
            options={
                'verbose_name': 'Discrepancia de Inventario',
                'verbose_name_plural': 'Discrepancias de Inventario',
                'ordering': ['-detectado_el'],
            },
        ),
    ]
