# Generated by Django 5.0.6 on 2026-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siaf_sincro', '0009_discrepanciainventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoalmacen',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Entrega'),
        ),
    ]
