# Generated by Django 5.0.2 on 2024-02-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='ruta',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='categoria',
            field=models.CharField(default='instructivo', max_length=100, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='titulo'),
        ),
    ]
