# Generated by Django 5.0.2 on 2024-02-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_instrumento_ruta_instrumento_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='categoria',
            field=models.CharField(max_length=100, null=True, verbose_name='categoria'),
        ),
    ]
