# Generated by Django 5.0.2 on 2024-02-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_instrumento_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('cargo', models.CharField(max_length=200, null=True, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='instrumento',
            options={'ordering': ['titulo'], 'verbose_name': 'Instrumento', 'verbose_name_plural': 'Instrumentos'},
        ),
        migrations.AddField(
            model_name='instrumento',
            name='fecha_publicacion',
            field=models.DateField(null=True, verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion'),
        ),
    ]
