# Generated by Django 5.0.2 on 2024-02-14 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_autor_alter_instrumento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='autor_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor'),
        ),
    ]
