# Generated by Django 5.0.2 on 2024-02-14 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_instrumento_autor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='autor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor'),
        ),
    ]
