# Generated by Django 5.0.2 on 2024-02-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_alter_instrumento_autor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de creacion'),
        ),
        migrations.RemoveField(
            model_name='instrumento',
            name='autor_id',
        ),
        migrations.AddField(
            model_name='instrumento',
            name='autor_id',
            field=models.ManyToManyField(to='biblioteca.autor'),
        ),
    ]
