# Generated by Django 5.0.2 on 2024-03-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_autor_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='documento',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='biblioteca/', verbose_name='documento'),
        ),
    ]
