# Generated by Django 5.0.2 on 2024-03-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_instrumento_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='documento',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='biblioteca/', verbose_name='documento'),
        ),
    ]
