# Generated by Django 5.0.2 on 2024-03-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_alter_instrumento_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='fecha_creacion',
            field=models.DateField(verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='fecha_publicacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de publicacion'),
        ),
    ]
