# Generated by Django 5.0.2 on 2024-03-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_alter_instrumento_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
