# Generated by Django 5.0.2 on 2024-03-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_instrumento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='portada',
            field=models.ImageField(blank=True, default='document_default.jpg', max_length=255, null=True, upload_to='portadas/', verbose_name='portada'),
        ),
    ]
